/********************************************************************
* THaDecDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THaDecDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHaDecDict();
extern void G__cpp_setup_inheritanceTHaDecDict();
extern void G__cpp_setup_typetableTHaDecDict();
extern void G__cpp_setup_memvarTHaDecDict();
extern void G__cpp_setup_globalTHaDecDict();
extern void G__cpp_setup_memfuncTHaDecDict();
extern void G__cpp_setup_funcTHaDecDict();
extern void G__set_cpp_environmentTHaDecDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "THaUsrstrutils.h"
#include "THaCrateMap.h"
#include "THaCodaData.h"
#include "THaHelicity.h"
#include "THaEpics.h"
#include "THaFastBusWord.h"
#include "THaCodaFile.h"
#include "THaSlotData.h"
#include "THaEvData.h"
#include "evio.h"
#include "THaCodaDecoder.h"
#include "THaBenchmark.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THaDecDictLN_TClass;
extern G__linked_taginfo G__THaDecDictLN_TBuffer;
extern G__linked_taginfo G__THaDecDictLN_TMemberInspector;
extern G__linked_taginfo G__THaDecDictLN_TObject;
extern G__linked_taginfo G__THaDecDictLN_string;
extern G__linked_taginfo G__THaDecDictLN_TString;
extern G__linked_taginfo G__THaDecDictLN_THaUsrstrutils;
extern G__linked_taginfo G__THaDecDictLN_THaCrateMap;
extern G__linked_taginfo G__THaDecDictLN_THaCrateMapcLcLECrateCode;
extern G__linked_taginfo G__THaDecDictLN_THaCodaData;
extern G__linked_taginfo G__THaDecDictLN_THaEvData;
extern G__linked_taginfo G__THaDecDictLN_THaHelicity;
extern G__linked_taginfo G__THaDecDictLN_vectorlEEpicsChancOallocatorlEEpicsChangRsPgR;
extern G__linked_taginfo G__THaDecDictLN_reverse_iteratorlEvectorlEEpicsChancOallocatorlEEpicsChangRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THaDecDictLN_maplEstringcOvectorlEEpicsChancOallocatorlEEpicsChangRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEEpicsChancOallocatorlEEpicsChangRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__THaDecDictLN_THaEpics;
extern G__linked_taginfo G__THaDecDictLN_THaFastBusWord;
extern G__linked_taginfo G__THaDecDictLN_THaFastBusWordcLcLmodule_information;
extern G__linked_taginfo G__THaDecDictLN_TArrayI;
extern G__linked_taginfo G__THaDecDictLN_THaCodaFile;
extern G__linked_taginfo G__THaDecDictLN_THaSlotData;
extern G__linked_taginfo G__THaDecDictLN_TBits;
extern G__linked_taginfo G__THaDecDictLN_THaBenchmark;
extern G__linked_taginfo G__THaDecDictLN_THaEvDatacLcLdA;
extern G__linked_taginfo G__THaDecDictLN_THaEvDatacLcLRocDat_t;
extern G__linked_taginfo G__THaDecDictLN_THaCodaDecoder;

/* STUB derived class for protected member access */
