/********************************************************************
* GreenMonsterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GreenMonsterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGreenMonsterDict();
extern void G__cpp_setup_inheritanceGreenMonsterDict();
extern void G__cpp_setup_typetableGreenMonsterDict();
extern void G__cpp_setup_memvarGreenMonsterDict();
extern void G__cpp_setup_globalGreenMonsterDict();
extern void G__cpp_setup_memfuncGreenMonsterDict();
extern void G__cpp_setup_funcGreenMonsterDict();
extern void G__set_cpp_environmentGreenMonsterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GreenMonster.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GreenMonsterDictLN_TClass;
extern G__linked_taginfo G__GreenMonsterDictLN_TBuffer;
extern G__linked_taginfo G__GreenMonsterDictLN_TMemberInspector;
extern G__linked_taginfo G__GreenMonsterDictLN_TObject;
extern G__linked_taginfo G__GreenMonsterDictLN_TString;
extern G__linked_taginfo G__GreenMonsterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GreenMonsterDictLN_TList;
extern G__linked_taginfo G__GreenMonsterDictLN_TTimer;
extern G__linked_taginfo G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GreenMonsterDictLN_TQObject;
extern G__linked_taginfo G__GreenMonsterDictLN_TQObjSender;
extern G__linked_taginfo G__GreenMonsterDictLN_TGWindow;
extern G__linked_taginfo G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GreenMonsterDictLN_TGObject;
extern G__linked_taginfo G__GreenMonsterDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GreenMonsterDictLN_TGFrame;
extern G__linked_taginfo G__GreenMonsterDictLN_TGCompositeFrame;
extern G__linked_taginfo G__GreenMonsterDictLN_TGTextButton;
extern G__linked_taginfo G__GreenMonsterDictLN_TGMainFrame;
extern G__linked_taginfo G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GreenMonsterDictLN_TGLabel;
extern G__linked_taginfo G__GreenMonsterDictLN_TGRadioButton;
extern G__linked_taginfo G__GreenMonsterDictLN_TGTextEntry;
extern G__linked_taginfo G__GreenMonsterDictLN_GreenTB;
extern G__linked_taginfo G__GreenMonsterDictLN_GreenADC;
extern G__linked_taginfo G__GreenMonsterDictLN_GreenADC18;
extern G__linked_taginfo G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR;
extern G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GreenMonsterDictLN_GreenVQWK;
extern G__linked_taginfo G__GreenMonsterDictLN_GreenMonster;

/* STUB derived class for protected member access */
