//
// File generated by rootcint at Tue Nov 13 10:52:40 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME GreenMonsterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GreenMonsterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void GreenMonster_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_GreenMonster(void *p);
   static void deleteArray_GreenMonster(void *p);
   static void destruct_GreenMonster(void *p);
   static void streamer_GreenMonster(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::GreenMonster*)
   {
      ::GreenMonster *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GreenMonster >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GreenMonster", ::GreenMonster::Class_Version(), "./GreenMonster.h", 76,
                  typeid(::GreenMonster), ::ROOT::DefineBehavior(ptr, ptr),
                  &::GreenMonster::Dictionary, isa_proxy, 0,
                  sizeof(::GreenMonster) );
      instance.SetDelete(&delete_GreenMonster);
      instance.SetDeleteArray(&deleteArray_GreenMonster);
      instance.SetDestructor(&destruct_GreenMonster);
      instance.SetStreamerFunc(&streamer_GreenMonster);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::GreenMonster*)
   {
      return GenerateInitInstanceLocal((::GreenMonster*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GreenMonster*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr GreenMonster::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *GreenMonster::Class_Name()
{
   return "GreenMonster";
}

//______________________________________________________________________________
const char *GreenMonster::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::GreenMonster*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GreenMonster::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::GreenMonster*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GreenMonster::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::GreenMonster*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GreenMonster::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::GreenMonster*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void GreenMonster::Streamer(TBuffer &R__b)
{
   // Stream an object of class GreenMonster.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void GreenMonster::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GreenMonster.
      TClass *R__cl = ::GreenMonster::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mainWidth", &mainWidth);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mainHeight", &mainHeight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "grnback", &grnback);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fUseCrate[5]", fUseCrate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fUseTB[5]", fUseTB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fUseADC[5]", fUseADC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fUseADCX[5]", fUseADCX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fUsevqwk[5]", fUsevqwk);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fUseSCAN[5]", fUseSCAN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCrateNames[5]", &fCrateNames);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCrateNumbers[5]", fCrateNumbers);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "scanCrate", &scanCrate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTimeBoard[5]", &fTimeBoard);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVQWK[5]", &fVQWK);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fADC[5]", &fADC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fADC18[5]", &fADC18);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBMW_TABID", &fBMW_TABID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*changeStatusBtBMW", &changeStatusBtBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*checkStatusBtBMW", &checkStatusBtBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*enableTestBtBMW", &enableTestBtBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*setKillBtBMW", &setKillBtBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*setValueBtBMW", &setValueBtBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*switchLabelBMW", &switchLabelBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*activeLabelBMW", &activeLabelBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*statusLabelBMW", &statusLabelBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTestObjRBtBMW[8]", &fTestObjRBtBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPntBMW", &tentSetPntBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chosenObjBMW", &chosenObjBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "testSetpointBMW", &testSetpointBMW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_ctimer", &_ctimer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fSCN_TABID", &fSCN_TABID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*setValueBtSCN", &setValueBtSCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*checkStatusBtSCN", &checkStatusBtSCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "statusSCN", &statusSCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "setpoint1SCN", &setpoint1SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "setpoint2SCN", &setpoint2SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "setpoint3SCN", &setpoint3SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "setpoint4SCN", &setpoint4SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "setpoint5SCN", &setpoint5SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fStateRBtSCN[2]", &fStateRBtSCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt1SCN", &tentSetPnt1SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt2SCN", &tentSetPnt2SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt3SCN", &tentSetPnt3SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt4SCN", &tentSetPnt4SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt5SCN", &tentSetPnt5SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt6SCN", &tentSetPnt6SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt7SCN", &tentSetPnt7SCN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tentSetPnt8SCN", &tentSetPnt8SCN);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_GreenMonster(void *p) {
      delete ((::GreenMonster*)p);
   }
   static void deleteArray_GreenMonster(void *p) {
      delete [] ((::GreenMonster*)p);
   }
   static void destruct_GreenMonster(void *p) {
      typedef ::GreenMonster current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_GreenMonster(TBuffer &buf, void *obj) {
      ((::GreenMonster*)obj)->::GreenMonster::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::GreenMonster

/********************************************************
* GreenMonsterDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGreenMonsterDict();

extern "C" void G__set_cpp_environmentGreenMonsterDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("GreenMonster.h");
  G__cpp_reset_tagtableGreenMonsterDict();
}
#include <new>
extern "C" int G__cpp_dllrevGreenMonsterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GreenMonster */
static int G__GreenMonsterDict_484_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const GreenMonster*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((GreenMonster*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((GreenMonster*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((GreenMonster*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((GreenMonster*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((GreenMonster*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   lval[icnt] = G__getstructoffset(); icnt++; // this pointer
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("EmitVA: more than 56 var args\n");
   }
      ((GreenMonster*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GreenMonster::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GreenMonster::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GreenMonster::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GreenMonster::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GreenMonster::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GreenMonster::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GreenMonster::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GreenMonster::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GreenMonster* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new GreenMonster(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) GreenMonster(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->BMWDelayCheck();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->BMWTestStep();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonsterDict_484_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GreenMonster*) G__getstructoffset())->Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GreenMonster G__TGreenMonster;
static int G__GreenMonsterDict_484_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GreenMonster*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GreenMonster*) (soff+(sizeof(GreenMonster)*i)))->~G__TGreenMonster();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GreenMonster*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GreenMonster*) (soff))->~G__TGreenMonster();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GreenMonster */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGreenMonsterDict {
 public:
  G__Sizep2memfuncGreenMonsterDict(): p(&G__Sizep2memfuncGreenMonsterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGreenMonsterDict::*p)();
};

size_t G__get_sizep2memfuncGreenMonsterDict()
{
  G__Sizep2memfuncGreenMonsterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGreenMonsterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster))) {
     GreenMonster *G__Lderived;
     G__Lderived=(GreenMonster*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGreenMonsterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGComboBox*>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GreenMonster */
static void G__setup_memvarGreenMonster(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster));
   { GreenMonster *p; p=(GreenMonster*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mainWidth=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mainHeight=",0,(char*)NULL);
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("ULong_t"),-1,4,"grnback=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fUseCrate[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fUseTB[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fUseADC[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fUseADCX[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fUsevqwk[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fUseSCAN[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TString),-1,-1,4,"fCrateNames[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fCrateNumbers[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"scanCrate=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenTB),-1,-1,4,"fTimeBoard[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenVQWK),-1,-1,4,"fVQWK[5]=",0,"Caryn add");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenADC),-1,-1,4,"fADC[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenADC18),-1,-1,4,"fADC18[5]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fBMW_TABID=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"changeStatusBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"checkStatusBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"enableTestBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"setKillBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"setValueBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGLabel),-1,-1,4,"switchLabelBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGLabel),-1,-1,4,"activeLabelBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGLabel),-1,-1,4,"statusLabelBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGRadioButton),-1,-1,4,"fTestObjRBtBMW[8]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPntBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"chosenObjBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"testSetpointBMW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TTimer),-1,-1,4,"_ctimer=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fSCN_TABID=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"setValueBtSCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"checkStatusBtSCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"statusSCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"setpoint1SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"setpoint2SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"setpoint3SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"setpoint4SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"setpoint5SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGRadioButton),-1,-1,4,"fStateRBtSCN[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt1SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt2SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt3SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt4SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt5SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt6SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt7SCN=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextEntry),-1,-1,4,"tentSetPnt8SCN=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGreenMonsterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGreenMonster(void) {
   /* GreenMonster */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster));
   G__memfunc_setup("GetListOfSignals",1602,G__GreenMonsterDict_484_0_1, 85, G__get_linked_tagnum(&G__GreenMonsterDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__GreenMonsterDict_484_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__GreenMonsterDict_484_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LowPriority",1172,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EmitVA",550,G__GreenMonsterDict_484_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__GreenMonsterDict_484_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChangedBy",869,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Message",709,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GreenMonsterDict_484_0_26, 85, G__get_linked_tagnum(&G__GreenMonsterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GreenMonster::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GreenMonsterDict_484_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GreenMonster::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GreenMonsterDict_484_0_28, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GreenMonster::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GreenMonsterDict_484_0_29, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GreenMonster::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GreenMonsterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GreenMonsterDict_484_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GreenMonsterDict_484_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GreenMonster::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GreenMonsterDict_484_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GreenMonster::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GreenMonsterDict_484_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GreenMonster::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GreenMonsterDict_484_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GreenMonster::DeclFileLine) ), 0);
   G__memfunc_setup("GreenMonster",1241,G__GreenMonsterDict_484_0_38, 105, G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ProcessMessage",1444,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"l - 'Long_t' 0 - msg l - 'Long_t' 0 - parm1 "
"l - 'Long_t' 0 - parm2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BMWDelayCheck",1203,G__GreenMonsterDict_484_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWTestStep",1058,G__GreenMonsterDict_484_0_41, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__GreenMonsterDict_484_0_42, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWDoRadio",904,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWCheckStatus",1352,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWChangeStatus",1456,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWActiveProbe",1338,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWCheckActiveFlag",1690,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWSetKill",926,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BMWStartTest",1172,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNDoRadio",902,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNUpdateStatus",1483,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNCheckStatus",1350,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNSetValues",1152,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNSetValue",1037,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i - 'Int_t' 0 - - i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNCheckValues",1330,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCNSetStatus",1172,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitGui",697,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GreenMonster", 1367, G__GreenMonsterDict_484_0_58, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGreenMonsterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGreenMonsterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGreenMonsterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GreenMonsterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenTB = { "GreenTB" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenADC = { "GreenADC" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenADC18 = { "GreenADC18" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR = { "vector<TGComboBox*,allocator<TGComboBox*> >" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_reverse_iteratorlEvectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGComboBox*,allocator<TGComboBox*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenVQWK = { "GreenVQWK" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenMonster = { "GreenMonster" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGreenMonsterDict() {
  G__GreenMonsterDictLN_TClass.tagnum = -1 ;
  G__GreenMonsterDictLN_TBuffer.tagnum = -1 ;
  G__GreenMonsterDictLN_TMemberInspector.tagnum = -1 ;
  G__GreenMonsterDictLN_TObject.tagnum = -1 ;
  G__GreenMonsterDictLN_TString.tagnum = -1 ;
  G__GreenMonsterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GreenMonsterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GreenMonsterDictLN_TList.tagnum = -1 ;
  G__GreenMonsterDictLN_TTimer.tagnum = -1 ;
  G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GreenMonsterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GreenMonsterDictLN_TQObject.tagnum = -1 ;
  G__GreenMonsterDictLN_TQObjSender.tagnum = -1 ;
  G__GreenMonsterDictLN_TGWindow.tagnum = -1 ;
  G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GreenMonsterDictLN_TGObject.tagnum = -1 ;
  G__GreenMonsterDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__GreenMonsterDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GreenMonsterDictLN_TGFrame.tagnum = -1 ;
  G__GreenMonsterDictLN_TGCompositeFrame.tagnum = -1 ;
  G__GreenMonsterDictLN_TGTextButton.tagnum = -1 ;
  G__GreenMonsterDictLN_TGMainFrame.tagnum = -1 ;
  G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__GreenMonsterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GreenMonsterDictLN_TGLabel.tagnum = -1 ;
  G__GreenMonsterDictLN_TGRadioButton.tagnum = -1 ;
  G__GreenMonsterDictLN_TGTextEntry.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenTB.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenADC.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenADC18.tagnum = -1 ;
  G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR.tagnum = -1 ;
  G__GreenMonsterDictLN_reverse_iteratorlEvectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenVQWK.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenMonster.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGreenMonsterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TList);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_GreenTB);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_GreenADC);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_GreenADC18);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_vectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_reverse_iteratorlEvectorlETGComboBoxmUcOallocatorlETGComboBoxmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_GreenVQWK);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GreenMonsterDictLN_GreenMonster),sizeof(GreenMonster),-1,62464,(char*)NULL,G__setup_memvarGreenMonster,G__setup_memfuncGreenMonster);
}
extern "C" void G__cpp_setupGreenMonsterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGreenMonsterDict()");
  G__set_cpp_environmentGreenMonsterDict();
  G__cpp_setup_tagtableGreenMonsterDict();

  G__cpp_setup_inheritanceGreenMonsterDict();

  G__cpp_setup_typetableGreenMonsterDict();

  G__cpp_setup_memvarGreenMonsterDict();

  G__cpp_setup_memfuncGreenMonsterDict();
  G__cpp_setup_globalGreenMonsterDict();
  G__cpp_setup_funcGreenMonsterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGreenMonsterDict();
  return;
}
class G__cpp_setup_initGreenMonsterDict {
  public:
    G__cpp_setup_initGreenMonsterDict() { G__add_setup_func("GreenMonsterDict",(G__incsetup)(&G__cpp_setupGreenMonsterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGreenMonsterDict() { G__remove_setup_func("GreenMonsterDict"); }
};
G__cpp_setup_initGreenMonsterDict G__cpp_setup_initializerGreenMonsterDict;

