#include "GreenTB.h"
#include <iostream>

GreenTB::GreenTB(Int_t crate_number, const char * crate_name,
		 const TGWindow *p, UInt_t w, UInt_t h) :
  TGCompositeFrame(p, w, h, kFixedSize), crateNumber(crate_number),
  CurrentRD(0), CurrentIT(0), CurrentOS(0) 
{
  crateName = new TString(crate_name);
}

GreenTB::~GreenTB() {
}


void GreenTB::Init(ULong_t backgrnd) {

  TGLayoutHints *framout = new TGLayoutHints(kLHintsTop | kLHintsExpandX | 
					     kLHintsExpandY, 5, 5, 5, 5);

  SetBackgroundColor(backgrnd);
  TGCompositeFrame *tcf1 = new TGGroupFrame(this, crateName->Data(), 
					     kVerticalFrame);
  tcf1->SetBackgroundColor(backgrnd);
  AddFrame(tcf1,framout);
  TGCompositeFrame *tcf1a = new TGHorizontalFrame(this,200,200);
  tcf1a->SetBackgroundColor(backgrnd);
  TGCompositeFrame *tcf1b = new TGHorizontalFrame(this,200,200);
  tcf1b->SetBackgroundColor(backgrnd);
  TGLayoutHints *fL_Top = new TGLayoutHints(kLHintsTop, 2, 2, 5, 1);
  tcf1->AddFrame(tcf1a,fL_Top);
  tcf1->AddFrame(tcf1b,fL_Top);
  tcf1a->SetLayoutManager(new TGMatrixLayout(tcf1a, 0, 2, 10));
  tcf1b->SetLayoutManager(new TGMatrixLayout(tcf1b, 1, 0, 10));

  // get starting values of tb
  CurrentRD = 0;
  CurrentIT = 0;
  CurrentOS = 0;

  // add text input fields to first page, 1st column
  char buff[6];

  TGLabel * lab;
  tcf1a->AddFrame(lab = new TGLabel(tcf1a, new TGHotString("Ramp Delay")));
  lab->SetBackgroundColor(backgrnd);
  sprintf(buff, "not set");
  TGTextBuffer *tbuf = new TGTextBuffer(6);
  tbuf->AddText(0,buff);
  tentRD = new TGTextEntry(tcf1a, tbuf, 221);
  tentRD->Resize(60, tentRD->GetDefaultHeight());
  tentRD->SetFont("-adobe-courier-bold-r-*-*-14-*-*-*-*-*-iso8859-1");
  tcf1a->AddFrame(tentRD);

  tcf1a->AddFrame(lab = new TGLabel(tcf1a, new TGHotString("Integrate Time")));
  lab->SetBackgroundColor(backgrnd);
  sprintf(buff, "not set");
  tbuf = new TGTextBuffer(6);
  tbuf->AddText(0,buff);
  tentIT = new TGTextEntry(tcf1a, tbuf, 222);
  tentIT->Resize(60, tentIT->GetDefaultHeight());
  tentIT->SetFont("-adobe-courier-bold-r-*-*-14-*-*-*-*-*-iso8859-1");
  tcf1a->AddFrame(tentIT);


  tcf1a->AddFrame(lab = new TGLabel(tcf1a, new TGHotString("Oversampling")));
  lab->SetBackgroundColor(backgrnd);
  sprintf(buff, "not set");
  tbuf = new TGTextBuffer(3);
  tbuf->AddText(0,buff);
  tentOS = new TGTextEntry(tcf1a, tbuf, 222);
  tentOS->Resize(40, tentOS->GetDefaultHeight());
  tentOS->SetFont("-adobe-courier-bold-r-*-*-14-*-*-*-*-*-iso8859-1");
  tcf1a->AddFrame(tentOS);

  tcf1->Resize(tcf1->GetDefaultSize());
  tcf1a->Resize(tcf1a->GetDefaultSize());

  TGTextButton *bt;


  tcf1b->AddFrame(bt = new TGTextButton(tcf1b,"Get Settings",GM_TB_GET));
  bt->Associate(this);
  bt->Resize(90, bt->GetDefaultHeight());
  bt->SetBackgroundColor(backgrnd);
  bt->SetToolTipText("Display updated information for this timing board");
  tcf1b->AddFrame(bt = new TGTextButton(tcf1b,"Apply Settings",GM_TB_SET));
  bt->SetBackgroundColor(backgrnd);
  bt->Associate(this);
  bt->Resize(90, bt->GetDefaultHeight());
  bt->SetToolTipText("Apply these settings to this timing board");

  tcf1b->Resize(tcf1b->GetDefaultSize());

  getValsTB();
}



Bool_t GreenTB::ProcessMessage(Long_t msg, Long_t parm1, Long_t parm2)
{
  // Process events generated by the buttons in the frame
    switch (GET_MSG(msg)) {
    case kC_COMMAND:
      switch (GET_SUBMSG(msg)) {
      case kCM_BUTTON:
	switch (parm1) 
	  {
	  case GM_TB_GET:
	    {
	      // Replace text entry fields with current values,
              // retrieved from TB
	      getValsTB();
	      //	      printf("Get Values button pressed\n");
	      break;
	    }
	  case GM_TB_SET:
	    {
	      setValsTB();
	      //	      printf("Set Values button pressed\n");
	      break;
	    }
	  default:
	    printf("text button id %ld pressed\n", parm1);
	    break;
	  }
	break;
      default:
	break;
      }
    default:
      break;
    }
  return kTRUE;
}

 Bool_t GreenTB::getValsTB() {
   // Replace text entry fields with current values,
   // retrieved from TB
   char buff[10];
   int errFlag;
   struct greenRequest gRequest;
   int command, par1, par2, par3, command_type;
   char *msgReq = (char *)"TB Get Data";
   char *reply = (char *)"Y";
  
   command_type = COMMAND_HAPTB;    gRequest.command_type = command_type;
   command = HAPTB_GET_DATA;        gRequest.command = command;
   par1 = HAPTB_RD;                 gRequest.par1 = par1;
   par2 = 0;                        gRequest.par2 = par2;
   par3 = 0;                        gRequest.par3 = par3;
   strcpy(gRequest.message,msgReq);   gRequest.reply = reply;

   printf("I am here where you thought I was");
   printf("COMMAND_HAPTB is %d \n",COMMAND_HAPTB); 

   errFlag = GreenSockCommand(crateNumber,&gRequest);
  
   printf ("cfSockCommand returned :  %d \n",errFlag);
   if (errFlag == SOCK_OK) {
     command = gRequest.command;
     par1 = gRequest.par1;
     par2 = gRequest.par2;
     CurrentRD = par2;
     sprintf(buff, "%i", par2);
     tentRD->SetText(buff);
   } else {
     std::cout << "ERROR accessing socket!" << std::endl;
   }
  
   command_type = COMMAND_HAPTB;    gRequest.command_type = command_type;
   command = HAPTB_GET_DATA;        gRequest.command = command;
   par1 = HAPTB_IT;                 gRequest.par1 = par1;
   par2 = 0;                        gRequest.par2 = par2;
   par3 = 0;                        gRequest.par3 = par3;
   strcpy(gRequest.message,msgReq);   gRequest.reply = reply;
   errFlag = GreenSockCommand(crateNumber,&gRequest);
   if (errFlag == SOCK_OK) {
     par2 = gRequest.par2;
     CurrentIT = par2;
     sprintf(buff, "%i", par2);
     tentIT->SetText(buff);
   } else {
     std::cout << "ERROR accessing socket!" << std::endl;
   }
  
   command_type = COMMAND_HAPTB;    gRequest.command_type = command_type;
   command = HAPTB_GET_DATA;        gRequest.command = command;
   par1 = HAPTB_OS;                 gRequest.par1 = par1;
   par2 = 0;                        gRequest.par2 = par2;
   par3 = 0;                        gRequest.par3 = par3;
   strcpy(gRequest.message,msgReq);   gRequest.reply = reply;
   errFlag = GreenSockCommand(crateNumber,&gRequest);
  
   if (errFlag == SOCK_OK) {
     par2 = gRequest.par2;
     CurrentOS = par2;
     sprintf(buff, "%i", par2);
     tentOS->SetText(buff);
   } else {
     std::cout << "ERROR accessing socket!" << std::endl;
   }
   return kTRUE;
 }


Bool_t GreenTB::setValsTB() {
  // Set current values of text entry fields to TB:
  Int_t replyFlag;
  int value;
  Bool_t success=kTRUE;
  
  value = atoi(tentRD->GetText());
  int NewRD = value;
  replyFlag = setParTB(HAPTB_RD,value);
  if (replyFlag==0) {
    CurrentRD=NewRD;
  } else if (replyFlag==2){
    std::cout << "Cannot set parameter, CODA run in progress" << std::endl;
    tentRD->SetText("RunInProgress");
    success = kFALSE;
  } else {
    std::cout << "Unknown error, cannot set TB parameter" << std::endl;
    tentRD->SetText("ERROR");
    success = kFALSE;
  }
  //printf("Ramp Delay is : %d \n",atoi(tentRD->GetText()));
  
  value = atoi(tentIT->GetText());
  int NewIT = value;
  replyFlag = setParTB(HAPTB_IT,value);
  if (replyFlag==0) {
    CurrentIT=NewIT;
  } else if (replyFlag==2){
    std::cout << "Cannot set parameter, CODA run in progress" << std::endl;
    tentIT->SetText("RunInProgress");
    success = kFALSE;
  } else {
    std::cout << "Unknown error, cannot set TB parameter" << std::endl;
    tentIT->SetText("ERROR");
    success = kFALSE;
  }
  //printf("Integrate Time is : %d \n",atoi(tentIT->GetText()));
    
  value = atoi(tentOS->GetText());
  int NewOS = value;
  replyFlag = setParTB(HAPTB_OS,value);
  if (replyFlag==0) {
    CurrentOS=NewOS;
  } else if (replyFlag==2){
    std::cout << "Cannot set parameter, CODA run in progress" << std::endl;
    tentOS->SetText("RunInProgress");
    success = kFALSE;
  } else {
    std::cout << "Unknown error, cannot set TB parameter" << std::endl;
    tentOS->SetText("ERROR");
    success = kFALSE;
  }
  
  return success;
}

Int_t GreenTB::setParTB(const int parNum, const int value) {
  // Set value of parameter on TB
  int errFlag;
  struct greenRequest gRequest;
  int command, command_type, par1, par2, par3;
  char *msgReq = (char *)"TB Set Data";
  char *reply = (char *)"Y";
  Int_t replyFlag = 0;
  
  command_type = COMMAND_HAPTB;    gRequest.command_type = command_type;
  command = HAPTB_SET_DATA;        gRequest.command = command;
  par1 = parNum;                   gRequest.par1 = par1;
  par2 = value;                    gRequest.par2 = par2;
  par3 = 0;                        gRequest.par3 = par3;
  strcpy(gRequest.message,msgReq);   gRequest.reply = reply;
  
  errFlag = GreenSockCommand(crateNumber,&gRequest);
  //  printf ("cfSockCommand returned :  %d \n",errFlag);
  if (errFlag == SOCK_OK) {
    //printf ("GM: MESSAGE FROM SERVER:\n%s\n", msgReq);
    if ((int) gRequest.command != 1) {
      if ((int) gRequest.command == -2) {
	// this should be CODA running error
	replyFlag = 2;
      } else {
	printf("Error:Server replied with TB error code: %d \n",
	       (int) gRequest.command);
	replyFlag = 1;
      }
    } else {
      if (parNum != (int) gRequest.par1) {
	printf("Server replied with wrong TB number: %d  instead of %d \n",
	       (int) gRequest.par1, parNum);
	replyFlag = 1;
      }
      if (value != (int) gRequest.par2) {
	printf("Server replied with wrong TB set value: %d instead of %d \n",
	       (int) gRequest.par2, value);
	replyFlag = 1;
	}
    }
  } else {
    printf("setParTB:: ERROR accessing socket!");
    replyFlag = 1;
  }
  return replyFlag;
}  


