#include "GreenVQWK.h"
#include <iostream>

GreenVQWK::GreenVQWK(Int_t crate_number, const char * crate_name,
		 const TGWindow *p, UInt_t w, UInt_t h) :
  TGCompositeFrame(p, w, h, kFixedSize), crateNumber(crate_number),
  CurrentSPB(0), CurrentGD(0), CurrentNB(0) 
{
  crateName = new TString(crate_name);
}

GreenVQWK::~GreenVQWK() {
}


void GreenVQWK::Init(ULong_t backgrnd) {

  TGLayoutHints *framout = new TGLayoutHints(kLHintsTop | kLHintsExpandX | 
					     kLHintsExpandY, 5, 5, 5, 5);

  SetBackgroundColor(backgrnd);
  TGCompositeFrame *tcf1 = new TGGroupFrame(this, crateName->Data(), 
					     kVerticalFrame);
  tcf1->SetBackgroundColor(backgrnd);
  AddFrame(tcf1,framout);
  TGCompositeFrame *tcf1a = new TGHorizontalFrame(this,200,200);
  tcf1a->SetBackgroundColor(backgrnd);
  TGCompositeFrame *tcf1b = new TGHorizontalFrame(this,200,200);
  tcf1b->SetBackgroundColor(backgrnd);
  TGLayoutHints *fL_Top = new TGLayoutHints(kLHintsTop, 2, 2, 5, 1);
  tcf1->AddFrame(tcf1a,fL_Top);
  tcf1->AddFrame(tcf1b,fL_Top);
  tcf1a->SetLayoutManager(new TGMatrixLayout(tcf1a, 0, 2, 10));
  tcf1b->SetLayoutManager(new TGMatrixLayout(tcf1b, 1, 0, 10));

  // get starting values of vqwk
  CurrentSPB = 0;
  CurrentGD = 0;
  CurrentNB = 0;

  // add text input fields to first page, 1st column
  char buff[6];

  TGLabel * lab;
  tcf1a->AddFrame(lab = new TGLabel(tcf1a, new TGHotString("Samples Per Block")));
  lab->SetBackgroundColor(backgrnd);
  sprintf(buff, "not set");
  TGTextBuffer *tbuf = new TGTextBuffer(6);
  tbuf->AddText(0,buff);
  tentSPB = new TGTextEntry(tcf1a, tbuf, 221);
  tentSPB->Resize(60, tentSPB->GetDefaultHeight());
  tentSPB->SetFont("-adobe-courier-bold-r-*-*-14-*-*-*-*-*-iso8859-1");
  tcf1a->AddFrame(tentSPB);

  tcf1a->AddFrame(lab = new TGLabel(tcf1a, new TGHotString("Gate Delay")));
  lab->SetBackgroundColor(backgrnd);
  sprintf(buff, "not set");
  tbuf = new TGTextBuffer(6);
  tbuf->AddText(0,buff);
  tentGD = new TGTextEntry(tcf1a, tbuf, 222);
  tentGD->Resize(60, tentGD->GetDefaultHeight());
  tentGD->SetFont("-adobe-courier-bold-r-*-*-14-*-*-*-*-*-iso8859-1");
  tcf1a->AddFrame(tentGD);


  tcf1a->AddFrame(lab = new TGLabel(tcf1a, new TGHotString("Number of Blocks")));
  lab->SetBackgroundColor(backgrnd);
  sprintf(buff, "not set");
  tbuf = new TGTextBuffer(3);
  tbuf->AddText(0,buff);
  tentNB = new TGTextEntry(tcf1a, tbuf, 222);
  tentNB->Resize(40, tentNB->GetDefaultHeight());
  tentNB->SetFont("-adobe-courier-bold-r-*-*-14-*-*-*-*-*-iso8859-1");
  tcf1a->AddFrame(tentNB);

  tcf1->Resize(tcf1->GetDefaultSize());
  tcf1a->Resize(tcf1a->GetDefaultSize());

  TGTextButton *bt;


  tcf1b->AddFrame(bt = new TGTextButton(tcf1b,"Get Settings",GM_VQWK_GET));
  bt->Associate(this);
  bt->Resize(90, bt->GetDefaultHeight());
  bt->SetBackgroundColor(backgrnd);
  bt->SetToolTipText("Display updated information for this vqwk adc");
  tcf1b->AddFrame(bt = new TGTextButton(tcf1b,"Apply Settings",GM_VQWK_SET));
  bt->SetBackgroundColor(backgrnd);
  bt->Associate(this);
  bt->Resize(90, bt->GetDefaultHeight());
  bt->SetToolTipText("Apply these settings to this vqwk adc");

  tcf1b->Resize(tcf1b->GetDefaultSize());

  getValsVQWK();
}



Bool_t GreenVQWK::ProcessMessage(Long_t msg, Long_t parm1, Long_t parm2)
{
  // Process events generated by the buttons in the frame
    switch (GET_MSG(msg)) {
    case kC_COMMAND:
      switch (GET_SUBMSG(msg)) {
      case kCM_BUTTON:
	switch (parm1) 
	  {
	  case GM_VQWK_GET:
	    {
	      // Replace text entry fields with current values,
              // retrieved from VQWK
	      getValsVQWK();
	      //	      printf("Get Values button pressed\n");
	      break;
	    }
	  case GM_VQWK_SET:
	    {
	      setValsVQWK(0);
              setValsVQWK(1);
	      setValsVQWK(2);
	      //	      printf("Set Values button pressed\n");
	      break;
	    }
	  default:
	    printf("text button id %ld pressed\n", parm1);
	    break;
	  }
	break;
      default:
	break;
      }
    default:
      break;
    }
  return kTRUE;
}

 Bool_t GreenVQWK::getValsVQWK() {
   // Replace text entry fields with current values,
   // retrieved from VQWK
   char buff[10];
   int errFlag;
   struct greenRequest gRequest;
   int command, par1, par2, par3, command_type;
   char *msgReq = (char *)"VQWK Get Data";
   char *reply = (char *)"Y";
  
   command_type = COMMAND_VQWK;    gRequest.command_type = command_type;
   command = VQWK_GET_DATA;        gRequest.command = command;
   par1 = VQWK_SPB;                 gRequest.par1 = par1;
   par2 = 0;                        gRequest.par2 = par2;
   par3 = 0;                        gRequest.par3 = par3;
   strcpy(gRequest.message,msgReq);   gRequest.reply = reply;

   // printf("I am here where you thought I was");
   //printf("COMMAND_VQWK is %d \n",COMMAND_VQWK); 

   errFlag = GreenSockCommand(crateNumber,&gRequest);
  
   //printf ("cfSockCommand returned :  %d \n",errFlag);
   if (errFlag == SOCK_OK) {
     command = gRequest.command;
     par1 = gRequest.par1;
     par2 = gRequest.par2;
     CurrentSPB = par2;
     sprintf(buff, "%i", par2);
     tentSPB->SetText(buff);
   } else {
     std::cout << "ERROR accessing socket!" << std::endl;
   }
  
   command_type = COMMAND_VQWK;    gRequest.command_type = command_type;
   command = VQWK_GET_DATA;        gRequest.command = command;
   par1 = VQWK_GD;                 gRequest.par1 = par1;
   par2 = 0;                        gRequest.par2 = par2;
   par3 = 0;                        gRequest.par3 = par3;
   strcpy(gRequest.message,msgReq);   gRequest.reply = reply;
   errFlag = GreenSockCommand(crateNumber,&gRequest);
   if (errFlag == SOCK_OK) {
     par2 = gRequest.par2;
     CurrentGD = par2;
     sprintf(buff, "%i", par2);
     tentGD->SetText(buff);
   } else {
     std::cout << "ERROR accessing socket!" << std::endl;
   }
  
   command_type = COMMAND_VQWK;    gRequest.command_type = command_type;
   command = VQWK_GET_DATA;        gRequest.command = command;
   par1 = VQWK_NB;                 gRequest.par1 = par1;
   par2 = 0;                        gRequest.par2 = par2;
   par3 = 0;                        gRequest.par3 = par3;
   strcpy(gRequest.message,msgReq);   gRequest.reply = reply;
   errFlag = GreenSockCommand(crateNumber,&gRequest);
  
   if (errFlag == SOCK_OK) {
     par2 = gRequest.par2;
     CurrentNB = par2;
     sprintf(buff, "%i", par2);
     tentNB->SetText(buff);
   } else {
     std::cout << "ERROR accessing socket!" << std::endl;
   }
   return kTRUE;
 }


Bool_t GreenVQWK::setValsVQWK(const int index) {
  // Set current values of text entry fields to VQWK:
  Int_t replyFlag;
  int value;
  Bool_t success=kTRUE;
  
  value = atoi(tentSPB->GetText());
  int NewSPB = value;
  replyFlag = setParVQWK(VQWK_SPB,value,index);
  if (replyFlag==0) {
    CurrentSPB=NewSPB;
  } else if (replyFlag==2){
    std::cout << "Cannot set parameter, CODA run in progress" << std::endl;
    tentSPB->SetText("RunInProgress");
    success = kFALSE;
  } else {
    std::cout << "Unknown error, cannot set VQWK parameter" << std::endl;
    tentSPB->SetText("ERROR");
    success = kFALSE;
  }
  //printf("Samples per block is : %d \n",atoi(tentSPB->GetText()));
  
  value = atoi(tentGD->GetText());
  int NewGD = value;
  replyFlag = setParVQWK(VQWK_GD,value,index);
  if (replyFlag==0) {
    CurrentGD=NewGD;
  } else if (replyFlag==2){
    std::cout << "Cannot set parameter, CODA run in progress" << std::endl;
    tentGD->SetText("RunInProgress");
    success = kFALSE;
  } else {
    std::cout << "Unknown error, cannot set VQWK parameter" << std::endl;
    tentGD->SetText("ERROR");
    success = kFALSE;
  }
  //printf("Gate Delay is : %d \n",atoi(tentGD->GetText()));
    
  value = atoi(tentNB->GetText());
  int NewNB = value;
  replyFlag = setParVQWK(VQWK_NB,value,index);
  if (replyFlag==0) {
    CurrentNB=NewNB;
  } else if (replyFlag==2){
    std::cout << "Cannot set parameter, CODA run in progress" << std::endl;
    tentNB->SetText("RunInProgress");
    success = kFALSE;
  } else {
    std::cout << "Unknown error, cannot set VQWK parameter" << std::endl;
    tentNB->SetText("ERROR");
    success = kFALSE;
  }
  
  return success;
}

Int_t GreenVQWK::setParVQWK(const int parNum, const int value, const int index) {
  // Set value of parameter on VQWK
  int errFlag;
  struct greenRequest gRequest;
  int command, command_type, par1, par2, par3;
  char *msgReq = (char *)"VQWK Set Data";
  char *reply = (char *)"Y";
  Int_t replyFlag = 0;

  command_type = COMMAND_VQWK;    gRequest.command_type = command_type;
  command = VQWK_SET_DATA;        gRequest.command = command;
  par1 = parNum;                   gRequest.par1 = par1;
  par2 = value;                    gRequest.par2 = par2;
  par3 = index;                        gRequest.par3 = par3;
  strcpy(gRequest.message,msgReq);   gRequest.reply = reply;
  
  errFlag = GreenSockCommand(crateNumber,&gRequest);
  //  printf ("cfSockCommand returned :  %d \n",errFlag);
  if (errFlag == SOCK_OK) {
    //printf ("GM: MESSAGE FROM SERVER:\n%s\n", msgReq);
    if ((int) gRequest.command != 1) {
      if ((int) gRequest.command == -2) {
	// this should be CODA running error
	replyFlag = 2;
      } else {
	printf("Error:Server replied with VQWK error code: %d \n",
	       (int) gRequest.command);
	replyFlag = 1;
      }
    } else {
      if (parNum != (int) gRequest.par1) {
	printf("Server replied with wrong VQWK number: %d  instead of %d \n",
	       (int) gRequest.par1, parNum);
	replyFlag = 1;
      }
      if (value != (int) gRequest.par2) {
	printf("Server replied with wrong VQWK set value: %d instead of %d \n",
	       (int) gRequest.par2, value);
	replyFlag = 1;
	}
    }
  } else {
    printf("setParVQWK:: ERROR accessing socket!");
    replyFlag = 1;
  }
  return replyFlag;
}  


