/********************************************************************
* THaScalDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error THaScalDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTHaScalDict();
extern void G__cpp_setup_inheritanceTHaScalDict();
extern void G__cpp_setup_typetableTHaScalDict();
extern void G__cpp_setup_memvarTHaScalDict();
extern void G__cpp_setup_globalTHaScalDict();
extern void G__cpp_setup_memfuncTHaScalDict();
extern void G__cpp_setup_funcTHaScalDict();
extern void G__set_cpp_environmentTHaScalDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "THaScaler.h"
#include "THaScalerDB.h"
#include "THaScalerGui.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__THaScalDictLN_TClass;
extern G__linked_taginfo G__THaScalDictLN_TBuffer;
extern G__linked_taginfo G__THaScalDictLN_TMemberInspector;
extern G__linked_taginfo G__THaScalDictLN_TObject;
extern G__linked_taginfo G__THaScalDictLN_string;
extern G__linked_taginfo G__THaScalDictLN_TString;
extern G__linked_taginfo G__THaScalDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_pairlEintcOintgR;
extern G__linked_taginfo G__THaScalDictLN_multimaplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_Bdate;
extern G__linked_taginfo G__THaScalDictLN_THaScalerDB;
extern G__linked_taginfo G__THaScalDictLN_THaCodaFile;
extern G__linked_taginfo G__THaScalDictLN_THaEvData;
extern G__linked_taginfo G__THaScalDictLN_TDatime;
extern G__linked_taginfo G__THaScalDictLN_THaScaler;
extern G__linked_taginfo G__THaScalDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THaScalDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THaScalDictLN_SDB_chanDesc;
extern G__linked_taginfo G__THaScalDictLN_SDB_directive;
extern G__linked_taginfo G__THaScalDictLN_pairlEintcOstringgR;
extern G__linked_taginfo G__THaScalDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_maplEpairlEintcOstringgRcOmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcOlesslEpairlEintcOstringgRsPgRcOallocatorlEpairlEconstsPpairlEintcOstringgRcOmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_maplESDB_chanKeycOSDB_chanDesccOlesslESDB_chanKeygRcOallocatorlEpairlEconstsPSDB_chanKeycOSDB_chanDescgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_pairlEpairlEintcOintgRcOintgR;
extern G__linked_taginfo G__THaScalDictLN_maplEpairlEpairlEintcOintgRcOintgRcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEpairlEpairlEintcOintgRcOintgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOintgRcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__THaScalDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__THaScalDictLN_maplEintcOTGTextEntrymUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGTextEntrymUgRsPgRsPgR;
extern G__linked_taginfo G__THaScalDictLN_maplEintcOTNtuplemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTNtuplemUgRsPgRsPgR;

/* STUB derived class for protected member access */
